// Critical Mass Training Program Data
// 9-day rotating cycle: 6 training days, 3 rest days
// Program start date: November 26, 2025

export const PROGRAM_START_DATE = '2025-11-26';

export const CYCLE_DAYS = [
  { day: 1, type: 'training', workout: 'push1', name: 'Push 1' },
  { day: 2, type: 'training', workout: 'legs1', name: 'Legs 1' },
  { day: 3, type: 'rest', workout: null, name: 'Rest' },
  { day: 4, type: 'training', workout: 'pull1', name: 'Pull 1' },
  { day: 5, type: 'training', workout: 'push2', name: 'Push 2' },
  { day: 6, type: 'rest', workout: null, name: 'Rest' },
  { day: 7, type: 'training', workout: 'legs2', name: 'Legs 2' },
  { day: 8, type: 'training', workout: 'pull2', name: 'Pull 2' },
  { day: 9, type: 'rest', workout: null, name: 'Rest' },
];

export const WORKOUTS = {
  push1: {
    id: 'push1',
    name: 'Push 1',
    focus: 'Chest, Side Delt – Hypertrophy focus | Front Delt, Triceps – PR focus',
    coreExercises: [
      {
        id: 'incline-bb-bench',
        name: 'Incline Barbell Bench Press',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'Take as many warm-ups as needed. Each set should be to positive failure.',
        variations: null,
      },
      {
        id: 'flat-db-bench',
        name: 'Flat Dumbbell Bench',
        sets: 3,
        repRange: '8-10',
        isPR: false,
        notes: 'Try to move up in weight when you can, but these are not PR sets—form should never suffer here.',
        variations: null,
      },
      {
        id: 'seated-lateral-raises',
        name: 'Seated Lateral Raises',
        sets: 5,
        repRange: '12-15',
        isPR: false,
        notes: 'Pick a weight where 15 reps is positive failure for the first set. Resting minimally, make sure you get at least 12 reps each set. Adjust your rest times so that each set gets at least 12 reps with the same weight.',
        variations: null,
      },
      {
        id: 'close-grip-bench',
        name: 'Close Grip Bench',
        sets: 2,
        repRange: '8-10',
        isPR: true,
        notes: 'Try to hit PRs, but make sure your triceps are doing the work—not your chest. PR options: More total reps over the 2 sets, more weight (once you get to 2 sets of 10 reps, increase the weight), or less rest between sets.',
        variations: null,
      },
      {
        id: 'seated-military-press',
        name: 'Seated Military Press',
        sets: 1,
        repRange: '10-12',
        isPR: true,
        notes: 'Perform warm ups as needed. This is a PR set—you must either get an additional rep or use more weight each time you cycle through.',
        variations: null,
      },
      {
        id: 'overhead-rope-extensions',
        name: 'Overhead Rope Extensions',
        sets: 3,
        repRange: '15-20',
        isPR: false,
        notes: 'Mechanical drop set. Start with hands separated. When you hit failure, keep hands separated on the eccentric but put hands together (for leverage) on the positive portion. When you hit failure there, keep hands together the entire time and bang out a few extra partial reps. This is essentially a triple drop set.',
        variations: null,
        isMechanicalDropSet: true,
        dropSetPhases: ['Hands Separated', 'Hands Together (pos)', 'Hands Together (full)'],
      },
      {
        id: 'pec-deck',
        name: 'Pec Deck',
        sets: 4,
        repRange: '20',
        isPR: false,
        notes: 'Pure blood volume here—get blood in the area. This is your hypertrophy day for chest, so push these HARD.',
        variations: ['Pec Deck', 'Cable Crossovers'],
      },
    ],
    additionalExercises: [
      { id: 'dips-push1', name: 'Dips', sets: 2, repRange: 'failure', notes: 'Learn to adjust based on your soreness. This is NOT a hypertrophy day for triceps. If your triceps are getting very sore, do not add this movement.' },
      { id: 'clean-press-push1', name: 'Clean and Presses', sets: 2, repRange: '12-15', notes: 'Hang clean to press. Adjust based on soreness.' },
    ],
    replacementExercises: [
      { id: 'cable-crossovers', name: 'Cable Crossovers', sets: 4, repRange: '20', notes: 'Replacement for Pec Deck when you hit sticking point on PRs.' },
      { id: 'incline-db-press-replace', name: 'Incline Dumbbell Presses', sets: 1, repRange: '8-10', notes: 'Replacement for Flat Barbell when you hit sticking point.' },
      { id: 'incline-bb-press-replace', name: 'Incline Barbell Presses', sets: 1, repRange: '8-10', notes: 'Replacement for Flat Barbell when you hit sticking point.' },
    ],
  },

  legs1: {
    id: 'legs1',
    name: 'Legs 1',
    focus: 'Quads, Calves – Hypertrophy focus | Hams, Adductors, Glutes – PR focus',
    coreExercises: [
      {
        id: 'standing-calf-l1',
        name: 'Standing Calf',
        sets: 4,
        repRange: '15-20',
        isPR: false,
        notes: 'Squeeze these—don\'t bounce. These aren\'t PR sets. Your goal is to contract the calf, not bounce up more weight.',
        variations: ['Machine', 'Smith Machine', 'Leg Press Calf Raise'],
      },
      {
        id: 'seated-calf-l1',
        name: 'Seated Calf',
        sets: 3,
        repRange: '15-20',
        isPR: false,
        notes: 'At the start of the movement, lean your body forward to place more weight over your feet. As the set gets harder, begin leaning back until you\'re actively pulling back on the handles to extend the set.',
        variations: null,
      },
      {
        id: 'walking-lunges-l1',
        name: 'Walking Lunges',
        sets: 3,
        repRange: '30 steps',
        isPR: false,
        notes: 'Warm up movement. 30 total steps per set.',
        variations: null,
      },
      {
        id: 'lying-leg-curls-l1',
        name: 'Lying Leg Curls',
        sets: 1,
        repRange: '10-12',
        isPR: true,
        notes: 'Add 1-2 forced reps, partial reps, and/or slow negative. This is a PR set, not a hypertrophy set so make sure you\'re putting everything into this one set and getting stronger each week.',
        variations: null,
      },
      {
        id: 'leg-press-l1',
        name: 'Leg Press',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: '2-3 warm-up sets of 10-20 reps first. These are hypertrophy sets so the focus is on FRYING the quads, not just pushing more weight. It\'s very easy to move up in weight here by tightening knee wraps, widening stance, not going as deep, etc. The goal is not to just use more weight—the goal is to make your quads sore.',
        variations: null,
      },
      {
        id: 'seated-leg-curls-l1',
        name: 'Seated Leg Curls',
        sets: 2,
        repRange: '10-15',
        isPR: true,
        notes: 'Your PR is the total reps with the same weight over the two sets (somewhere between 20-30 reps). A PR is more total reps than the previous workout.',
        variations: null,
      },
      {
        id: 'leg-ext-squat-superset',
        name: 'Leg Extension + Barbell Squat Superset',
        sets: 3,
        repRange: '20 ext / 10 squat',
        isPR: false,
        notes: 'These should be brutal. The leg extensions are to positive failure. The squat should follow IMMEDIATELY (within 10 seconds) of finishing the leg extensions.',
        variations: null,
        isSuperset: true,
        supersetExercises: [
          { name: 'Leg Extension', repRange: '20' },
          { name: 'Barbell Squat', repRange: '10' },
        ],
      },
      {
        id: 'adductor-machine-l1',
        name: 'Adductor Machine',
        sets: 1,
        repRange: '20',
        isPR: true,
        notes: 'This is a PR set so get stronger each week.',
        variations: null,
      },
    ],
    additionalExercises: [
      { id: 'wide-sldl', name: 'Wide Stance Stiff Leg Deadlifts', sets: 3, repRange: '12-15', notes: 'A few reps short of failure. Supplement volume for PR body parts.' },
      { id: 'bulgarian-l1', name: 'Bulgarian Split Squats', sets: 1, repRange: '20/leg', notes: 'Do NOT turn each body part into a hypertrophy-focused body part by adding volume to every PR-focused body part or you will stall progress.' },
      { id: 'single-leg-press-l1', name: 'Single Leg Press', sets: 2, repRange: '15-20', notes: '' },
      { id: 'hack-squat-l1', name: 'Hack Squats', sets: 1, repRange: '15-20', notes: '' },
    ],
    replacementExercises: [],
  },

  pull1: {
    id: 'pull1',
    name: 'Pull 1',
    focus: 'Lats, Rear Delts, Biceps – Hypertrophy focus | Mid/Lower Back, Traps – PR focus',
    warmUp: 'Do a few sets of pull downs or cable pull overs to get blood in the lats and muscles around the shoulder.',
    coreExercises: [
      {
        id: 'pullups',
        name: 'Pull Ups',
        sets: 5,
        repRange: 'failure',
        isPR: true,
        notes: 'Start with as few reps as you need to. If you\'re a larger bodybuilder who hasn\'t done pullups in a long time, you might be doing sets of 5 reps to start. That\'s fine. Whatever the total rep count is for a given workout, you must get more the next week. E.g., if you get 25 total reps in the first workout, then 26 total reps in the next is a PR. Only if you don\'t force the new reps. Counting half reps as a PR is going to lead to a sticking point and stall progress.',
        variations: null,
      },
      {
        id: 'deadlift-variation',
        name: 'Deadlifts / Rack Pulls / Pendlay Rows',
        sets: 2,
        repRange: '5-8, 10-12',
        isPR: true,
        notes: 'Warm ups: as many as needed to get to your max weight. Just like on squats, you have more than one movement to work with. If you\'re feeling strong on deads, always use those as the primary movement. If your legs are too sore from the leg workout, use rack pulls as your backup movement. If you\'re not feeling strong at all, use Pendlay rows and find a way to grind out another rep on the higher rep set. Pendlay rows are a deadlift/bent over row combination—start each set from the ground as a deadlift and it turns into a bent row as it passes your knees.',
        variations: ['Deadlifts', 'Rack Pulls', 'Pendlay Rows'],
      },
      {
        id: 'rope-pulldowns',
        name: 'Rope Pull Downs',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'Done with the rope attachment—the one you would typically use for triceps pushdowns. This is almost a hybrid pullover/pulldown movement. Adjust your form until you feel your lats being the prime mover. This is not a weight movement—the lats are a weak link in this position so you will need to be very focused on making sure they are pulling the rope handles down and not the other muscles of the back.',
        variations: null,
      },
      {
        id: 'shrugs-p1',
        name: 'Shrugs',
        sets: 3,
        repRange: '15',
        isPR: false,
        notes: 'Work through these sets with minimal rest.',
        variations: ['Barbell', 'Dumbbell', 'Machine'],
      },
      {
        id: 'kroc-rows',
        name: 'One Arm Rows (Kroc Rows)',
        sets: 1,
        repRange: '15',
        isPR: false,
        notes: 'Done similarly to a standard one-arm row, but you will do them without a knee on a bench. You\'ll lean forward with your opposite hand on a bench or dumbbell rack. You will pronate your hands slightly so that the dumbbell is perpendicular to your torso (similarly to how your hand would be angled to hold a barbell in a barbell row). This allows for better leverages and heavier weight.',
        variations: null,
      },
      {
        id: 'reverse-pec-deck',
        name: 'Reverse Pec Deck',
        sets: 5,
        repRange: '15',
        isPR: false,
        notes: '',
        variations: null,
      },
      {
        id: 'preacher-curls',
        name: 'Preacher Curls',
        sets: 4,
        repRange: '15-20',
        isPR: false,
        notes: 'Form is everything here—these are not PR sets. These are to fry your biceps.',
        variations: null,
      },
      {
        id: 'drag-curls',
        name: 'Drag Curls',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'There are many videos online of drag curl form—you basically just do a barbell curl while dragging the bar along your body.',
        variations: null,
      },
    ],
    additionalExercises: [
      { id: 'seated-rows-p1', name: 'Seated Rows', sets: 3, repRange: '10-15', notes: 'Adjust based on soreness.' },
      { id: 'hs-pulldowns-p1', name: 'Hammer Strength Pulldowns', sets: 3, repRange: '10-12', notes: 'Any pulldown or row variation.' },
      { id: 'cable-curls-p1', name: 'Cable Curls', sets: 6, repRange: '6', notes: 'Done one arm at a time—essentially one very long set where you rotate between arms for 6 sets of each arm. Only perform an additional bicep movement on EITHER the Pull 1 or Pull 2 workouts—not both.' },
    ],
    replacementExercises: [],
  },

  push2: {
    id: 'push2',
    name: 'Push 2',
    focus: 'Delt, Triceps – Hypertrophy focus | Chest – PR focus',
    coreExercises: [
      {
        id: 'machine-press',
        name: 'Machine Press',
        sets: 3,
        repRange: '5-7',
        isPR: true,
        notes: 'Typically a hammer press is best. On the 3 sets of 5-7 reps, you have multiple ways of achieving a PR: 1) Increasing the total number of reps over the three sets. E.g., if you did 3x5 (15 total) this week, then 1x6 + 2x5 (16 total) next week is a PR. 2) Increasing the weight once you hit 7 reps in all three sets. 3) Increasing the weight on the first set only, then completing the second two sets with the same weight and reps as the previous week.',
        variations: ['Hammer Press', 'Plate Loaded', 'Cable Machine'],
      },
      {
        id: 'incline-db-bench-p2',
        name: 'Incline Dumbbell Bench',
        sets: 2,
        repRange: '6-8, 10-12',
        isPR: true,
        notes: 'These are PR sets, but form should not suffer. Keep yourself injury free, but get stronger each week.',
        variations: null,
      },
      {
        id: 'cable-lateral-raises',
        name: 'Cable Lateral Raises',
        sets: 3,
        repRange: '12-15',
        isPR: false,
        notes: '',
        variations: null,
      },
      {
        id: 'dead-stop-skull-crushers',
        name: 'Dead-Stop Skull Crushers (Floor)',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'Each rep should pause briefly on the floor, like in a deadlift.',
        variations: null,
      },
      {
        id: 'one-arm-btn-smith',
        name: 'One Arm Behind-the-Neck Smith Machine Press',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'Performed on a traditional smith machine, but only one arm is used. The machine will still run smoothly along the bearings of each side—the arm being used does not need to be placed in the center of the bar.',
        variations: null,
      },
      {
        id: 'db-front-raise',
        name: 'Dumbbell Front Raise',
        sets: 3,
        repRange: '12-15',
        isPR: false,
        notes: 'Don\'t swing these up. If you\'re not doing dumbbell shoulder press with 200lb dumbbells, you won\'t be able to contract your front delts to use more than about 70lb dumbbells here. If you\'re using more than that, you\'re swinging the weight and making it a trap movement.',
        variations: null,
      },
      {
        id: 'machine-dips',
        name: 'Machine Dips',
        sets: 4,
        repRange: '20',
        isPR: false,
        notes: '',
        variations: null,
      },
      {
        id: 'tricep-pushdowns',
        name: 'Triceps Pushdowns',
        sets: 3,
        repRange: '10-15',
        isPR: false,
        notes: '',
        variations: null,
      },
    ],
    additionalExercises: [
      { id: 'dips-push2', name: 'Dips', sets: 2, repRange: 'failure', notes: 'Adjust based on your soreness. This is NOT a hypertrophy day for Chest. If your Chest is getting sore from this workout then you\'re not going to benefit from the hypertrophy work in the Push 1 session.' },
      { id: 'clean-press-push2', name: 'Clean and Presses', sets: 2, repRange: '12-15', notes: 'Hang clean to press.' },
    ],
    replacementExercises: [],
  },

  legs2: {
    id: 'legs2',
    name: 'Legs 2',
    focus: 'Hams, Adductors, Glutes, Calves – Hypertrophy focus | Quads – PR focus',
    coreExercises: [
      {
        id: 'standing-calf-l2',
        name: 'Standing Calf',
        sets: 3,
        repRange: '15-20',
        isPR: false,
        notes: 'Squeeze these—don\'t bounce. These aren\'t PR sets. Your goal is to contract the calf, not bounce up more weight.',
        variations: ['Machine', 'Smith Machine', 'Leg Press Calf Raise'],
      },
      {
        id: 'seated-calf-l2',
        name: 'Seated Calf',
        sets: 3,
        repRange: '15-20',
        isPR: false,
        notes: '',
        variations: null,
      },
      {
        id: 'walking-lunges-l2',
        name: 'Walking Lunges',
        sets: 3,
        repRange: '30 steps',
        isPR: false,
        notes: 'Warm up movement.',
        variations: null,
      },
      {
        id: 'lying-leg-curls-l2',
        name: 'Lying Leg Curls',
        sets: 4,
        repRange: '10-12',
        isPR: false,
        notes: 'Use as many warm-ups as needed. These are done to positive failure—not beyond that.',
        variations: null,
      },
      {
        id: 'squat-l2',
        name: 'Squat (Back or Front)',
        sets: 2,
        repRange: '5-7, 10-12',
        isPR: true,
        notes: 'Rotate between back squat and front squat as needed to always hit a PR. The goal is to get stronger every week, but ONLY if your form is unchanged. If you\'re putting the bar lower on your back, widening your stance, or resting 10 minutes in between sets to get a PR, you\'re not getting stronger—you\'re just more rested or have better leverage.',
        variations: ['Back Squat', 'Front Squat'],
      },
      {
        id: 'db-leg-curls',
        name: 'Dumbbell Leg Curls',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'Place a dumbbell between the soles of your feet. There are many videos online if you have trouble figuring the movement out.',
        variations: null,
      },
      {
        id: 'leg-press-high-wide',
        name: 'Leg Press (High & Wide)',
        sets: 4,
        repRange: '15-20',
        isPR: false,
        notes: 'Put your feet high and wide on the leg press and arch your lower back. You should feel these in your glutes, adductors, and also hamstrings.',
        variations: null,
      },
      {
        id: 'hack-squat-l2',
        name: 'Hack Squat',
        sets: 1,
        repRange: '12-15',
        isPR: true,
        notes: 'Use as many warm-ups as needed, but if you\'re not warm by this part of the workout, something is terribly wrong. Focus on getting stronger without any change in the movement.',
        variations: null,
      },
    ],
    additionalExercises: [
      { id: 'bulgarian-l2', name: 'Bulgarian Split Squats', sets: 1, repRange: '20/leg', notes: 'Quads are your PR movement for the day. It\'s very hard to get stronger on quads without also making them sore—so be very sure you truly need the additional workload before you add an additional movement.' },
      { id: 'single-leg-press-l2', name: 'Single Leg Press', sets: 2, repRange: '15-20', notes: '' },
    ],
    replacementExercises: [],
  },

  pull2: {
    id: 'pull2',
    name: 'Pull 2',
    focus: 'Mid/Lower Back, Traps – Hypertrophy focus | Lats, Rear Delts, Biceps – PR focus',
    warmUp: 'Perform a few sets of cable pull overs or light pulldowns to get the muscles of the back and shoulder properly warm and ready for the training session.',
    coreExercises: [
      {
        id: 'pulldowns-p2',
        name: 'Pull Downs (Overhand)',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'Focus on squeezing the lats. Pulldowns aren\'t a strength movement. Spread the scapula and then contract the lats. That is the goal here. If we can get stronger in that form—great. But don\'t sacrifice the contraction for weight.',
        variations: null,
      },
      {
        id: 'rack-pulls-p2',
        name: 'Rack Pulls',
        sets: 2,
        repRange: '5-7, 10-12',
        isPR: true,
        notes: 'Use as many warm-ups as necessary. I don\'t really care where you put the bar—it can be below the knee, at the knee, or even at the top of the knee. This isn\'t an ego lift and you don\'t get brownie points for putting the pins lower on your lower leg. This movement is to make your midback freakishly strong—so pick the pin location for that, not for internet points. Lower than that and I might as well have just done a regular deadlift because the weights used would have been the same.',
        variations: null,
      },
      {
        id: 'tbar-rows',
        name: 'T-Bar Rows',
        sets: 4,
        repRange: '10-12',
        isPR: true,
        notes: '2-3 sets not to failure, then 1 PR set. Keep some semblance of form but get f\'n strong on these.',
        variations: null,
      },
      {
        id: 'wide-bent-rows',
        name: 'Wide Bent Over Rows',
        sets: 3,
        repRange: '10-12',
        isPR: false,
        notes: 'Stand on a box if needed. These are bent over rows with a wider grip (a lot wider) where you stay bent over past parallel to the floor. You pull to the chest on these.',
        variations: null,
      },
      {
        id: 'bb-curls-rp',
        name: 'Barbell Curls (Rest Pause)',
        sets: 1,
        repRange: '15-20 total',
        isPR: false,
        notes: '1-2 warm up sets to get blood in the area and then right into the main set. This is a rest-pause set.',
        variations: null,
      },
      {
        id: 'db-hammer-curls',
        name: 'Dumbbell Hammer Curls',
        sets: 1,
        repRange: '15-20',
        isPR: false,
        notes: 'Straight set, not rest pause. Start with both arms at the same time. When you get close to failure, begin alternating arms for more momentum and leverage.',
        variations: null,
      },
      {
        id: 'rear-delt-swings',
        name: 'Rear Delt Dumbbell Swings',
        sets: 2,
        repRange: '12-15',
        isPR: false,
        notes: 'Lay facing down on an incline bench and use dumbbells about twice as heavy as you would for standard bent over laterals. Keeping your arms straight, attempt to perform a rear lateral. You\'ll only be able to move the weight about 15 degrees—but that\'s the movement. Try to swing them out as far to the side as possible.',
        variations: null,
      },
    ],
    additionalExercises: [
      { id: 'hs-pulldowns-p2', name: 'Hammer Strength Pulldowns', sets: 3, repRange: '10-12', notes: 'Any variation.' },
      { id: 'hs-rows-p2', name: 'Hammer Strength Rows', sets: 3, repRange: '8-10', notes: 'Any variation.' },
      { id: 'machine-curls-p2', name: 'Machine Curls', sets: 6, repRange: '6', notes: 'Perform an additional bicep movement on EITHER Pull 1 or Pull 2, not both. This is meant to alternate between arms, so it would be essentially one very long set where you do 6 reps back and forth between arms.' },
    ],
    replacementExercises: [],
  },
};
